image: jangorecki/r-pkg

test:
  script:
    - R -e 'install.packages(c("jsonlite", "data.table", "dplyr", "magrittr", "ggplot2", "DT", "testthat"))'
    - R CMD build .
    - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
    - R CMD check "${PKG_FILE_NAME}" --no-manual --as-cran